### ISSUE TITLE
[Feature Request] Option for Export

### ISSUE THREAD

**Issue by Novack** [oleg-shilo/DocPreview.VSIX#9]
I find the extension perfect for my needs, simply parsing any given code file for its doc comments.
Much appreciated work!

I'd like to ask for a new option on the toolbar: to export the generated html to some external file, along with the css.

Currently, Im manually doing it: inspecting the source, saving it on a folder as an html file, then copying the css file on the same folder.

Would be possible? Thanks!

**Comment by oleg-shilo** [comment]
Conceptually... no problems. 
Though would this work flow be sufficient?
- Generate the documentation for the whole active document. This will open generate static html file and open it in your web browser.
- Export the generated file from your browser. All browsers can do this:

![image](https://user-images.githubusercontent.com/16729806/51438844-939b9600-1d05-11e9-876b-d1756e4df870.png)

**Comment by Novack** [comment]
Hey @oleg-shilo thank you for coming back on this.

What you propose is exactly what needed! No reason for more options really, the problem for me was that the "generate the documentation for the whole active document" option was not working, so I had no idea what it actually did.

I just checked #8 and it seems that you have been working on it, thanks a ton! Looking forward to try it.

**Comment by oleg-shilo** [comment]
Great, but... to make sure we are on the same page. I am not working on #8 because it's not a defect.

The system works as expected. Simply in your case the XML content that you are trying to export is not a valid XML so exporting fails. 

Though... I have added a better error handling to assist with the problems as described in #8. Thus it is more obvious, which XML segment is playing up. 

![image](https://user-images.githubusercontent.com/16729806/51468119-429da780-1dc2-11e9-985b-f4830b33c7f2.png)

![image](https://user-images.githubusercontent.com/16729806/51468170-66f98400-1dc2-11e9-9c8d-274488752d94.png)

The update has been published yesterday and you can now already upgrade your plugin copy.

**Comment by Novack** [comment]
Thanks a ton. I think it is a bit odd nonetheless, because I have corrected all the XML fails, and now each individual comment renders correctly when shown one by one, it just silently fails when I try to export them as a whole. 
I'll update the plugin and report back, hopefully will help me find out what the problem lies.

**Comment by Novack** [comment]
Ok, it finally worked. It seems that one comment on the class, was using triple slash, but was not a intended xml, and had no tags. The new error reporting popup helps great deal.

The file produced incorrectly sets the path to the CSS, and so only loads plain text, but that is easily solved once saved.

Thanks a ton.
